/* Data gathered from https://gist.github.com/Miserlou/11500b2345d3fe850c92 */
DROP TABLE IF EXISTS dbo.city_state;

CREATE TABLE dbo.city_state (
	city_name NVARCHAR(50) NOT NULL,
	state_name NVARCHAR(50) NOT NULL
		CONSTRAINT uq_dbo_city_state UNIQUE (city_name, state_name)
);

INSERT INTO dbo.city_state(city_name, state_name)
SELECT 
	 a.city, a.state
FROM 
(
VALUES
	(N'Abilene',N'Texas'),
	(N'Addison',N'Illinois'),
	(N'Akron',N'Ohio'),
	(N'Alameda',N'California'),
	(N'Albany',N'Georgia'),
	(N'Albany',N'New York'),
	(N'Albany',N'Oregon'),
	(N'Albuquerque',N'New Mexico'),
	(N'Alexandria',N'Louisiana'),
	(N'Alexandria',N'Virginia'),
	(N'Alhambra',N'California'),
	(N'Aliso Viejo',N'California'),
	(N'Allen',N'Texas'),
	(N'Allentown',N'Pennsylvania'),
	(N'Alpharetta',N'Georgia'),
	(N'Altamonte Springs',N'Florida'),
	(N'Altoona',N'Pennsylvania'),
	(N'Amarillo',N'Texas'),
	(N'Ames',N'Iowa'),
	(N'Anaheim',N'California'),
	(N'Anchorage',N'Alaska'),
	(N'Anderson',N'Indiana'),
	(N'Ankeny',N'Iowa'),
	(N'Ann Arbor',N'Michigan'),
	(N'Annapolis',N'Maryland'),
	(N'Antioch',N'California'),
	(N'Apache Junction',N'Arizona'),
	(N'Apex',N'North Carolina'),
	(N'Apopka',N'Florida'),
	(N'Apple Valley',N'California'),
	(N'Apple Valley',N'Minnesota'),
	(N'Appleton',N'Wisconsin'),
	(N'Arcadia',N'California'),
	(N'Arlington',N'Texas'),
	(N'Arlington Heights',N'Illinois'),
	(N'Arvada',N'Colorado'),
	(N'Asheville',N'North Carolina'),
	(N'Athens-Clarke County',N'Georgia'),
	(N'Atlanta',N'Georgia'),
	(N'Atlantic City',N'New Jersey'),
	(N'Attleboro',N'Massachusetts'),
	(N'Auburn',N'Alabama'),
	(N'Auburn',N'Washington'),
	(N'Augusta-Richmond County',N'Georgia'),
	(N'Aurora',N'Colorado'),
	(N'Aurora',N'Illinois'),
	(N'Austin',N'Texas'),
	(N'Aventura',N'Florida'),
	(N'Avondale',N'Arizona'),
	(N'Azusa',N'California'),
	(N'Bakersfield',N'California'),
	(N'Baldwin Park',N'California'),
	(N'Baltimore',N'Maryland'),
	(N'Barnstable Town',N'Massachusetts'),
	(N'Bartlett',N'Illinois'),
	(N'Bartlett',N'Tennessee'),
	(N'Baton Rouge',N'Louisiana'),
	(N'Battle Creek',N'Michigan'),
	(N'Bayonne',N'New Jersey'),
	(N'Baytown',N'Texas'),
	(N'Beaumont',N'California'),
	(N'Beaumont',N'Texas'),
	(N'Beavercreek',N'Ohio'),
	(N'Beaverton',N'Oregon'),
	(N'Bedford',N'Texas'),
	(N'Bell Gardens',N'California'),
	(N'Belleville',N'Illinois'),
	(N'Bellevue',N'Nebraska'),
	(N'Bellevue',N'Washington'),
	(N'Bellflower',N'California'),
	(N'Bellingham',N'Washington'),
	(N'Beloit',N'Wisconsin'),
	(N'Bend',N'Oregon'),
	(N'Bentonville',N'Arkansas'),
	(N'Berkeley',N'California'),
	(N'Berwyn',N'Illinois'),
	(N'Bethlehem',N'Pennsylvania'),
	(N'Beverly',N'Massachusetts'),
	(N'Billings',N'Montana'),
	(N'Biloxi',N'Mississippi'),
	(N'Binghamton',N'New York'),
	(N'Birmingham',N'Alabama'),
	(N'Bismarck',N'North Dakota'),
	(N'Blacksburg',N'Virginia'),
	(N'Blaine',N'Minnesota'),
	(N'Bloomington',N'Illinois'),
	(N'Bloomington',N'Indiana'),
	(N'Bloomington',N'Minnesota'),
	(N'Blue Springs',N'Missouri'),
	(N'Boca Raton',N'Florida'),
	(N'Boise City',N'Idaho'),
	(N'Bolingbrook',N'Illinois'),
	(N'Bonita Springs',N'Florida'),
	(N'Bossier City',N'Louisiana'),
	(N'Boston',N'Massachusetts'),
	(N'Boulder',N'Colorado'),
	(N'Bountiful',N'Utah'),
	(N'Bowie',N'Maryland'),
	(N'Bowling Green',N'Kentucky'),
	(N'Boynton Beach',N'Florida'),
	(N'Bozeman',N'Montana'),
	(N'Bradenton',N'Florida'),
	(N'Brea',N'California'),
	(N'Bremerton',N'Washington'),
	(N'Brentwood',N'California'),
	(N'Brentwood',N'Tennessee'),
	(N'Bridgeport',N'Connecticut'),
	(N'Bristol',N'Connecticut'),
	(N'Brockton',N'Massachusetts'),
	(N'Broken Arrow',N'Oklahoma'),
	(N'Brookfield',N'Wisconsin'),
	(N'Brookhaven',N'Georgia'),
	(N'Brooklyn Park',N'Minnesota'),
	(N'Broomfield',N'Colorado'),
	(N'Brownsville',N'Texas'),
	(N'Bryan',N'Texas'),
	(N'Buckeye',N'Arizona'),
	(N'Buena Park',N'California'),
	(N'Buffalo',N'New York'),
	(N'Buffalo Grove',N'Illinois'),
	(N'Bullhead City',N'Arizona'),
	(N'Burbank',N'California'),
	(N'Burien',N'Washington'),
	(N'Burleson',N'Texas'),
	(N'Burlington',N'North Carolina'),
	(N'Burlington',N'Vermont'),
	(N'Burnsville',N'Minnesota'),
	(N'Caldwell',N'Idaho'),
	(N'Calexico',N'California'),
	(N'Calumet City',N'Illinois'),
	(N'Camarillo',N'California'),
	(N'Cambridge',N'Massachusetts'),
	(N'Camden',N'New Jersey'),
	(N'Campbell',N'California'),
	(N'Canton',N'Ohio'),
	(N'Cape Coral',N'Florida'),
	(N'Cape Girardeau',N'Missouri'),
	(N'Carlsbad',N'California'),
	(N'Carmel',N'Indiana'),
	(N'Carol Stream',N'Illinois'),
	(N'Carpentersville',N'Illinois'),
	(N'Carrollton',N'Texas'),
	(N'Carson',N'California'),
	(N'Carson City',N'Nevada'),
	(N'Cary',N'North Carolina'),
	(N'Casa Grande',N'Arizona'),
	(N'Casper',N'Wyoming'),
	(N'Castle Rock',N'Colorado'),
	(N'Cathedral City',N'California'),
	(N'Cedar Falls',N'Iowa'),
	(N'Cedar Hill',N'Texas'),
	(N'Cedar Park',N'Texas'),
	(N'Cedar Rapids',N'Iowa'),
	(N'Centennial',N'Colorado'),
	(N'Ceres',N'California'),
	(N'Cerritos',N'California'),
	(N'Champaign',N'Illinois'),
	(N'Chandler',N'Arizona'),
	(N'Chapel Hill',N'North Carolina'),
	(N'Charleston',N'South Carolina'),
	(N'Charleston',N'West Virginia'),
	(N'Charlotte',N'North Carolina'),
	(N'Charlottesville',N'Virginia'),
	(N'Chattanooga',N'Tennessee'),
	(N'Chelsea',N'Massachusetts'),
	(N'Chesapeake',N'Virginia'),
	(N'Chesterfield',N'Missouri'),
	(N'Cheyenne',N'Wyoming'),
	(N'Chicago',N'Illinois'),
	(N'Chico',N'California'),
	(N'Chicopee',N'Massachusetts'),
	(N'Chino',N'California'),
	(N'Chino Hills',N'California'),
	(N'Chula Vista',N'California'),
	(N'Cicero',N'Illinois'),
	(N'Cincinnati',N'Ohio'),
	(N'Citrus Heights',N'California'),
	(N'Clarksville',N'Tennessee'),
	(N'Clearwater',N'Florida'),
	(N'Cleveland',N'Ohio'),
	(N'Cleveland',N'Tennessee'),
	(N'Cleveland Heights',N'Ohio'),
	(N'Clifton',N'New Jersey'),
	(N'Clovis',N'California'),
	(N'Clovis',N'New Mexico'),
	(N'Coachella',N'California'),
	(N'Coconut Creek',N'Florida'),
	(N'Coeur d''Alene',N'Idaho'),
	(N'College Station',N'Texas'),
	(N'Collierville',N'Tennessee'),
	(N'Colorado Springs',N'Colorado'),
	(N'Colton',N'California'),
	(N'Columbia',N'Missouri'),
	(N'Columbia',N'South Carolina'),
	(N'Columbus',N'Georgia'),
	(N'Columbus',N'Indiana'),
	(N'Columbus',N'Ohio'),
	(N'Commerce City',N'Colorado'),
	(N'Compton',N'California'),
	(N'Concord',N'California'),
	(N'Concord',N'New Hampshire'),
	(N'Concord',N'North Carolina'),
	(N'Conroe',N'Texas'),
	(N'Conway',N'Arkansas'),
	(N'Coon Rapids',N'Minnesota'),
	(N'Coppell',N'Texas'),
	(N'Coral Gables',N'Florida'),
	(N'Coral Springs',N'Florida'),
	(N'Corona',N'California'),
	(N'Corpus Christi',N'Texas'),
	(N'Corvallis',N'Oregon'),
	(N'Costa Mesa',N'California'),
	(N'Council Bluffs',N'Iowa'),
	(N'Covina',N'California'),
	(N'Covington',N'Kentucky'),
	(N'Cranston',N'Rhode Island'),
	(N'Crystal Lake',N'Illinois'),
	(N'Culver City',N'California'),
	(N'Cupertino',N'California'),
	(N'Cutler Bay',N'Florida'),
	(N'Cuyahoga Falls',N'Ohio'),
	(N'Cypress',N'California'),
	(N'Dallas',N'Texas'),
	(N'Daly City',N'California'),
	(N'Danbury',N'Connecticut'),
	(N'Danville',N'California'),
	(N'Danville',N'Virginia'),
	(N'Davenport',N'Iowa'),
	(N'Davie',N'Florida'),
	(N'Davis',N'California'),
	(N'Dayton',N'Ohio'),
	(N'Daytona Beach',N'Florida'),
	(N'Dearborn',N'Michigan'),
	(N'Dearborn Heights',N'Michigan'),
	(N'Decatur',N'Alabama'),
	(N'Decatur',N'Illinois'),
	(N'Deerfield Beach',N'Florida'),
	(N'DeKalb',N'Illinois'),
	(N'Delano',N'California'),
	(N'Delray Beach',N'Florida'),
	(N'Deltona',N'Florida'),
	(N'Denton',N'Texas'),
	(N'Denver',N'Colorado'),
	(N'Des Moines',N'Iowa'),
	(N'Des Plaines',N'Illinois'),
	(N'DeSoto',N'Texas'),
	(N'Detroit',N'Michigan'),
	(N'Diamond Bar',N'California'),
	(N'Doral',N'Florida'),
	(N'Dothan',N'Alabama'),
	(N'Dover',N'Delaware'),
	(N'Downers Grove',N'Illinois'),
	(N'Downey',N'California'),
	(N'Draper',N'Utah'),
	(N'Dublin',N'California'),
	(N'Dublin',N'Ohio'),
	(N'Dubuque',N'Iowa'),
	(N'Duluth',N'Minnesota'),
	(N'Duncanville',N'Texas'),
	(N'Dunwoody',N'Georgia'),
	(N'Durham',N'North Carolina'),
	(N'Eagan',N'Minnesota'),
	(N'East Lansing',N'Michigan'),
	(N'East Orange',N'New Jersey'),
	(N'East Providence',N'Rhode Island'),
	(N'Eastvale',N'California'),
	(N'Eau Claire',N'Wisconsin'),
	(N'Eden Prairie',N'Minnesota'),
	(N'Edina',N'Minnesota'),
	(N'Edinburg',N'Texas'),
	(N'Edmond',N'Oklahoma'),
	(N'Edmonds',N'Washington'),
	(N'El Cajon',N'California'),
	(N'El Centro',N'California'),
	(N'El Monte',N'California'),
	(N'El Paso',N'Texas'),
	(N'Elgin',N'Illinois'),
	(N'Elizabeth',N'New Jersey'),
	(N'Elk Grove',N'California'),
	(N'Elkhart',N'Indiana'),
	(N'Elmhurst',N'Illinois'),
	(N'Elyria',N'Ohio'),
	(N'Encinitas',N'California'),
	(N'Enid',N'Oklahoma'),
	(N'Erie',N'Pennsylvania'),
	(N'Escondido',N'California'),
	(N'Euclid',N'Ohio'),
	(N'Eugene',N'Oregon'),
	(N'Euless',N'Texas'),
	(N'Evanston',N'Illinois'),
	(N'Evansville',N'Indiana'),
	(N'Everett',N'Massachusetts'),
	(N'Everett',N'Washington'),
	(N'Fairfield',N'California'),
	(N'Fairfield',N'Ohio'),
	(N'Fall River',N'Massachusetts'),
	(N'Fargo',N'North Dakota'),
	(N'Farmington',N'New Mexico'),
	(N'Farmington Hills',N'Michigan'),
	(N'Fayetteville',N'Arkansas'),
	(N'Fayetteville',N'North Carolina'),
	(N'Federal Way',N'Washington'),
	(N'Findlay',N'Ohio'),
	(N'Fishers',N'Indiana'),
	(N'Fitchburg',N'Massachusetts'),
	(N'Flagstaff',N'Arizona'),
	(N'Flint',N'Michigan'),
	(N'Florence',N'Alabama'),
	(N'Florence',N'South Carolina'),
	(N'Florissant',N'Missouri'),
	(N'Flower Mound',N'Texas'),
	(N'Folsom',N'California'),
	(N'Fond du Lac',N'Wisconsin'),
	(N'Fontana',N'California'),
	(N'Fort Collins',N'Colorado'),
	(N'Fort Lauderdale',N'Florida'),
	(N'Fort Myers',N'Florida'),
	(N'Fort Pierce',N'Florida'),
	(N'Fort Smith',N'Arkansas'),
	(N'Fort Wayne',N'Indiana'),
	(N'Fort Worth',N'Texas'),
	(N'Fountain Valley',N'California'),
	(N'Franklin',N'Tennessee'),
	(N'Frederick',N'Maryland'),
	(N'Freeport',N'New York'),
	(N'Fremont',N'California'),
	(N'Fresno',N'California'),
	(N'Friendswood',N'Texas'),
	(N'Frisco',N'Texas'),
	(N'Fullerton',N'California'),
	(N'Gainesville',N'Florida'),
	(N'Gaithersburg',N'Maryland'),
	(N'Galveston',N'Texas'),
	(N'Garden Grove',N'California'),
	(N'Gardena',N'California'),
	(N'Garland',N'Texas'),
	(N'Gary',N'Indiana'),
	(N'Gastonia',N'North Carolina'),
	(N'Georgetown',N'Texas'),
	(N'Germantown',N'Tennessee'),
	(N'Gilbert',N'Arizona'),
	(N'Gilroy',N'California'),
	(N'Glendale',N'Arizona'),
	(N'Glendale',N'California'),
	(N'Glendora',N'California'),
	(N'Glenview',N'Illinois'),
	(N'Goodyear',N'Arizona'),
	(N'Goose Creek',N'South Carolina'),
	(N'Grand Forks',N'North Dakota'),
	(N'Grand Island',N'Nebraska'),
	(N'Grand Junction',N'Colorado'),
	(N'Grand Prairie',N'Texas'),
	(N'Grand Rapids',N'Michigan'),
	(N'Grapevine',N'Texas'),
	(N'Great Falls',N'Montana'),
	(N'Greeley',N'Colorado'),
	(N'Green Bay',N'Wisconsin'),
	(N'Greenacres',N'Florida'),
	(N'Greenfield',N'Wisconsin'),
	(N'Greensboro',N'North Carolina'),
	(N'Greenville',N'North Carolina'),
	(N'Greenville',N'South Carolina'),
	(N'Greenwood',N'Indiana'),
	(N'Gresham',N'Oregon'),
	(N'Grove City',N'Ohio'),
	(N'Gulfport',N'Mississippi'),
	(N'Hackensack',N'New Jersey'),
	(N'Hagerstown',N'Maryland'),
	(N'Hallandale Beach',N'Florida'),
	(N'Haltom City',N'Texas'),
	(N'Hamilton',N'Ohio'),
	(N'Hammond',N'Indiana'),
	(N'Hampton',N'Virginia'),
	(N'Hanford',N'California'),
	(N'Hanover Park',N'Illinois'),
	(N'Harlingen',N'Texas'),
	(N'Harrisburg',N'Pennsylvania'),
	(N'Harrisonburg',N'Virginia'),
	(N'Hartford',N'Connecticut'),
	(N'Hattiesburg',N'Mississippi'),
	(N'Haverhill',N'Massachusetts'),
	(N'Hawthorne',N'California'),
	(N'Hayward',N'California'),
	(N'Hemet',N'California'),
	(N'Hempstead',N'New York'),
	(N'Henderson',N'Nevada'),
	(N'Hendersonville',N'Tennessee'),
	(N'Hesperia',N'California'),
	(N'Hialeah',N'Florida'),
	(N'Hickory',N'North Carolina'),
	(N'High Point',N'North Carolina'),
	(N'Highland',N'California'),
	(N'Hillsboro',N'Oregon'),
	(N'Hilton Head Island',N'South Carolina'),
	(N'Hoboken',N'New Jersey'),
	(N'Hoffman Estates',N'Illinois'),
	(N'Hollywood',N'Florida'),
	(N'Holyoke',N'Massachusetts'),
	(N'Homestead',N'Florida'),
	(N'Honolulu',N'Hawaii'),
	(N'Hoover',N'Alabama'),
	(N'Houston',N'Texas'),
	(N'Huber Heights',N'Ohio'),
	(N'Huntersville',N'North Carolina'),
	(N'Huntington',N'West Virginia'),
	(N'Huntington Beach',N'California'),
	(N'Huntington Park',N'California'),
	(N'Huntsville',N'Alabama'),
	(N'Huntsville',N'Texas'),
	(N'Hurst',N'Texas'),
	(N'Hutchinson',N'Kansas'),
	(N'Idaho Falls',N'Idaho'),
	(N'Independence',N'Missouri'),
	(N'Indianapolis',N'Indiana'),
	(N'Indio',N'California'),
	(N'Inglewood',N'California'),
	(N'Iowa City',N'Iowa'),
	(N'Irvine',N'California'),
	(N'Irving',N'Texas'),
	(N'Jackson',N'Mississippi'),
	(N'Jackson',N'Tennessee'),
	(N'Jacksonville',N'Florida'),
	(N'Jacksonville',N'North Carolina'),
	(N'Janesville',N'Wisconsin'),
	(N'Jefferson City',N'Missouri'),
	(N'Jeffersonville',N'Indiana'),
	(N'Jersey City',N'New Jersey'),
	(N'Johns Creek',N'Georgia'),
	(N'Johnson City',N'Tennessee'),
	(N'Joliet',N'Illinois'),
	(N'Jonesboro',N'Arkansas'),
	(N'Joplin',N'Missouri'),
	(N'Jupiter',N'Florida'),
	(N'Jurupa Valley',N'California'),
	(N'Kalamazoo',N'Michigan'),
	(N'Kannapolis',N'North Carolina'),
	(N'Kansas City',N'Kansas'),
	(N'Kansas City',N'Missouri'),
	(N'Kearny',N'New Jersey'),
	(N'Keizer',N'Oregon'),
	(N'Keller',N'Texas'),
	(N'Kenner',N'Louisiana'),
	(N'Kennewick',N'Washington'),
	(N'Kenosha',N'Wisconsin'),
	(N'Kent',N'Washington'),
	(N'Kentwood',N'Michigan'),
	(N'Kettering',N'Ohio'),
	(N'Killeen',N'Texas'),
	(N'Kingsport',N'Tennessee'),
	(N'Kirkland',N'Washington'),
	(N'Kissimmee',N'Florida'),
	(N'Knoxville',N'Tennessee'),
	(N'Kokomo',N'Indiana'),
	(N'La Crosse',N'Wisconsin'),
	(N'La Habra',N'California'),
	(N'La Mesa',N'California'),
	(N'La Mirada',N'California'),
	(N'La Puente',N'California'),
	(N'La Quinta',N'California'),
	(N'Lacey',N'Washington'),
	(N'Lafayette',N'Indiana'),
	(N'Lafayette',N'Louisiana'),
	(N'Laguna Niguel',N'California'),
	(N'Lake Charles',N'Louisiana'),
	(N'Lake Elsinore',N'California'),
	(N'Lake Forest',N'California'),
	(N'Lake Havasu City',N'Arizona'),
	(N'Lake Oswego',N'Oregon'),
	(N'Lakeland',N'Florida'),
	(N'Lakeville',N'Minnesota'),
	(N'Lakewood',N'California'),
	(N'Lakewood',N'Colorado'),
	(N'Lakewood',N'Ohio'),
	(N'Lakewood',N'Washington'),
	(N'Lancaster',N'California'),
	(N'Lancaster',N'Ohio'),
	(N'Lancaster',N'Pennsylvania'),
	(N'Lancaster',N'Texas'),
	(N'Lansing',N'Michigan'),
	(N'Laredo',N'Texas'),
	(N'Largo',N'Florida'),
	(N'Las Cruces',N'New Mexico'),
	(N'Las Vegas',N'Nevada'),
	(N'Lauderhill',N'Florida'),
	(N'Lawrence',N'Indiana'),
	(N'Lawrence',N'Kansas'),
	(N'Lawrence',N'Massachusetts'),
	(N'Lawton',N'Oklahoma'),
	(N'Layton',N'Utah'),
	(N'League City',N'Texas'),
	(N'Lee''s Summit',N'Missouri'),
	(N'Leesburg',N'Virginia'),
	(N'Lehi',N'Utah'),
	(N'Lenexa',N'Kansas'),
	(N'Leominster',N'Massachusetts'),
	(N'Lewisville',N'Texas'),
	(N'Lexington-Fayette',N'Kentucky'),
	(N'Lima',N'Ohio'),
	(N'Lincoln',N'California'),
	(N'Lincoln',N'Nebraska'),
	(N'Lincoln Park',N'Michigan'),
	(N'Linden',N'New Jersey'),
	(N'Little Rock',N'Arkansas'),
	(N'Littleton',N'Colorado'),
	(N'Livermore',N'California'),
	(N'Livonia',N'Michigan'),
	(N'Lodi',N'California'),
	(N'Logan',N'Utah'),
	(N'Lombard',N'Illinois'),
	(N'Lompoc',N'California'),
	(N'Long Beach',N'California'),
	(N'Longmont',N'Colorado'),
	(N'Longview',N'Texas'),
	(N'Lorain',N'Ohio'),
	(N'Los Angeles',N'California'),
	(N'Louisville/Jefferson County',N'Kentucky'),
	(N'Loveland',N'Colorado'),
	(N'Lowell',N'Massachusetts'),
	(N'Lubbock',N'Texas'),
	(N'Lynchburg',N'Virginia'),
	(N'Lynn',N'Massachusetts'),
	(N'Lynwood',N'California'),
	(N'Macon',N'Georgia'),
	(N'Madera',N'California'),
	(N'Madison',N'Alabama'),
	(N'Madison',N'Wisconsin'),
	(N'Malden',N'Massachusetts'),
	(N'Manassas',N'Virginia'),
	(N'Manchester',N'New Hampshire'),
	(N'Manhattan',N'Kansas'),
	(N'Mankato',N'Minnesota'),
	(N'Mansfield',N'Ohio'),
	(N'Mansfield',N'Texas'),
	(N'Manteca',N'California'),
	(N'Maple Grove',N'Minnesota'),
	(N'Maplewood',N'Minnesota'),
	(N'Marana',N'Arizona'),
	(N'Margate',N'Florida'),
	(N'Maricopa',N'Arizona'),
	(N'Marietta',N'Georgia'),
	(N'Marlborough',N'Massachusetts'),
	(N'Martinez',N'California'),
	(N'Marysville',N'Washington'),
	(N'McAllen',N'Texas'),
	(N'McKinney',N'Texas'),
	(N'Medford',N'Massachusetts'),
	(N'Medford',N'Oregon'),
	(N'Melbourne',N'Florida'),
	(N'Memphis',N'Tennessee'),
	(N'Menifee',N'California'),
	(N'Mentor',N'Ohio'),
	(N'Merced',N'California'),
	(N'Meriden',N'Connecticut'),
	(N'Meridian',N'Idaho'),
	(N'Meridian',N'Mississippi'),
	(N'Mesa',N'Arizona'),
	(N'Mesquite',N'Texas'),
	(N'Methuen',N'Massachusetts'),
	(N'Miami',N'Florida'),
	(N'Miami Beach',N'Florida'),
	(N'Miami Gardens',N'Florida'),
	(N'Middletown',N'Connecticut'),
	(N'Middletown',N'Ohio'),
	(N'Midland',N'Michigan'),
	(N'Midland',N'Texas'),
	(N'Midwest City',N'Oklahoma'),
	(N'Milford',N'Connecticut'),
	(N'Milpitas',N'California'),
	(N'Milwaukee',N'Wisconsin'),
	(N'Minneapolis',N'Minnesota'),
	(N'Minnetonka',N'Minnesota'),
	(N'Minot',N'North Dakota'),
	(N'Miramar',N'Florida'),
	(N'Mishawaka',N'Indiana'),
	(N'Mission',N'Texas'),
	(N'Mission Viejo',N'California'),
	(N'Missoula',N'Montana'),
	(N'Missouri City',N'Texas'),
	(N'Mobile',N'Alabama'),
	(N'Modesto',N'California'),
	(N'Moline',N'Illinois'),
	(N'Monroe',N'Louisiana'),
	(N'Monrovia',N'California'),
	(N'Montclair',N'California'),
	(N'Montebello',N'California'),
	(N'Monterey Park',N'California'),
	(N'Montgomery',N'Alabama'),
	(N'Moore',N'Oklahoma'),
	(N'Moorhead',N'Minnesota'),
	(N'Moreno Valley',N'California'),
	(N'Morgan Hill',N'California'),
	(N'Mount Pleasant',N'South Carolina'),
	(N'Mount Prospect',N'Illinois'),
	(N'Mount Vernon',N'New York'),
	(N'Mountain View',N'California'),
	(N'Muncie',N'Indiana'),
	(N'Murfreesboro',N'Tennessee'),
	(N'Murray',N'Utah'),
	(N'Murrieta',N'California'),
	(N'Muskegon',N'Michigan'),
	(N'Muskogee',N'Oklahoma'),
	(N'Nampa',N'Idaho'),
	(N'Napa',N'California'),
	(N'Naperville',N'Illinois'),
	(N'Nashua',N'New Hampshire'),
	(N'Nashville-Davidson',N'Tennessee'),
	(N'National City',N'California'),
	(N'New Bedford',N'Massachusetts'),
	(N'New Berlin',N'Wisconsin'),
	(N'New Braunfels',N'Texas'),
	(N'New Britain',N'Connecticut'),
	(N'New Brunswick',N'New Jersey'),
	(N'New Haven',N'Connecticut'),
	(N'New Orleans',N'Louisiana'),
	(N'New Rochelle',N'New York'),
	(N'New York',N'New York'),
	(N'Newark',N'California'),
	(N'Newark',N'New Jersey'),
	(N'Newark',N'Ohio'),
	(N'Newport Beach',N'California'),
	(N'Newport News',N'Virginia'),
	(N'Newton',N'Massachusetts'),
	(N'Niagara Falls',N'New York'),
	(N'Noblesville',N'Indiana'),
	(N'Norfolk',N'Virginia'),
	(N'Normal',N'Illinois'),
	(N'Norman',N'Oklahoma'),
	(N'North Charleston',N'South Carolina'),
	(N'North Las Vegas',N'Nevada'),
	(N'North Lauderdale',N'Florida'),
	(N'North Little Rock',N'Arkansas'),
	(N'North Miami',N'Florida'),
	(N'North Miami Beach',N'Florida'),
	(N'North Port',N'Florida'),
	(N'North Richland Hills',N'Texas'),
	(N'Northglenn',N'Colorado'),
	(N'Norwalk',N'California'),
	(N'Norwalk',N'Connecticut'),
	(N'Norwich',N'Connecticut'),
	(N'Novato',N'California'),
	(N'Novi',N'Michigan'),
	(N'Oak Lawn',N'Illinois'),
	(N'Oak Park',N'Illinois'),
	(N'Oakland',N'California'),
	(N'Oakland Park',N'Florida'),
	(N'Oakley',N'California'),
	(N'Ocala',N'Florida'),
	(N'Oceanside',N'California'),
	(N'Ocoee',N'Florida'),
	(N'Odessa',N'Texas'),
	(N'O''Fallon',N'Missouri'),
	(N'Ogden',N'Utah'),
	(N'Oklahoma City',N'Oklahoma'),
	(N'Olathe',N'Kansas'),
	(N'Olympia',N'Washington'),
	(N'Omaha',N'Nebraska'),
	(N'Ontario',N'California'),
	(N'Orange',N'California'),
	(N'Orem',N'Utah'),
	(N'Orland Park',N'Illinois'),
	(N'Orlando',N'Florida'),
	(N'Ormond Beach',N'Florida'),
	(N'Oro Valley',N'Arizona'),
	(N'Oshkosh',N'Wisconsin'),
	(N'Overland Park',N'Kansas'),
	(N'Owensboro',N'Kentucky'),
	(N'Oxnard',N'California'),
	(N'Pacifica',N'California'),
	(N'Palatine',N'Illinois'),
	(N'Palm Bay',N'Florida'),
	(N'Palm Beach Gardens',N'Florida'),
	(N'Palm Coast',N'Florida'),
	(N'Palm Desert',N'California'),
	(N'Palm Springs',N'California'),
	(N'Palmdale',N'California'),
	(N'Palo Alto',N'California'),
	(N'Panama City',N'Florida'),
	(N'Paramount',N'California'),
	(N'Park Ridge',N'Illinois'),
	(N'Parker',N'Colorado'),
	(N'Parma',N'Ohio'),
	(N'Pasadena',N'California'),
	(N'Pasadena',N'Texas'),
	(N'Pasco',N'Washington'),
	(N'Passaic',N'New Jersey'),
	(N'Paterson',N'New Jersey'),
	(N'Pawtucket',N'Rhode Island'),
	(N'Peabody',N'Massachusetts'),
	(N'Peachtree Corners',N'Georgia'),
	(N'Pearland',N'Texas'),
	(N'Pembroke Pines',N'Florida'),
	(N'Pensacola',N'Florida'),
	(N'Peoria',N'Arizona'),
	(N'Peoria',N'Illinois'),
	(N'Perris',N'California'),
	(N'Perth Amboy',N'New Jersey'),
	(N'Petaluma',N'California'),
	(N'Pflugerville',N'Texas'),
	(N'Pharr',N'Texas'),
	(N'Phenix City',N'Alabama'),
	(N'Philadelphia',N'Pennsylvania'),
	(N'Phoenix',N'Arizona'),
	(N'Pico Rivera',N'California'),
	(N'Pine Bluff',N'Arkansas'),
	(N'Pinellas Park',N'Florida'),
	(N'Pittsburg',N'California'),
	(N'Pittsburgh',N'Pennsylvania'),
	(N'Pittsfield',N'Massachusetts'),
	(N'Placentia',N'California'),
	(N'Plainfield',N'Illinois'),
	(N'Plainfield',N'New Jersey'),
	(N'Plano',N'Texas'),
	(N'Plantation',N'Florida'),
	(N'Pleasanton',N'California'),
	(N'Plymouth',N'Minnesota'),
	(N'Pocatello',N'Idaho'),
	(N'Pomona',N'California'),
	(N'Pompano Beach',N'Florida'),
	(N'Pontiac',N'Michigan'),
	(N'Port Arthur',N'Texas'),
	(N'Port Orange',N'Florida'),
	(N'Port St. Lucie',N'Florida'),
	(N'Portage',N'Michigan'),
	(N'Porterville',N'California'),
	(N'Portland',N'Maine'),
	(N'Portland',N'Oregon'),
	(N'Portsmouth',N'Virginia'),
	(N'Poway',N'California'),
	(N'Prescott',N'Arizona'),
	(N'Prescott Valley',N'Arizona'),
	(N'Providence',N'Rhode Island'),
	(N'Provo',N'Utah'),
	(N'Pueblo',N'Colorado'),
	(N'Puyallup',N'Washington'),
	(N'Quincy',N'Illinois'),
	(N'Quincy',N'Massachusetts'),
	(N'Racine',N'Wisconsin'),
	(N'Raleigh',N'North Carolina'),
	(N'Rancho Cordova',N'California'),
	(N'Rancho Cucamonga',N'California'),
	(N'Rancho Palos Verdes',N'California'),
	(N'Rancho Santa Margarita',N'California'),
	(N'Rapid City',N'South Dakota'),
	(N'Reading',N'Pennsylvania'),
	(N'Redding',N'California'),
	(N'Redlands',N'California'),
	(N'Redmond',N'Washington'),
	(N'Redondo Beach',N'California'),
	(N'Redwood City',N'California'),
	(N'Reno',N'Nevada'),
	(N'Renton',N'Washington'),
	(N'Revere',N'Massachusetts'),
	(N'Rialto',N'California'),
	(N'Richardson',N'Texas'),
	(N'Richland',N'Washington'),
	(N'Richmond',N'California'),
	(N'Richmond',N'Virginia'),
	(N'Rio Rancho',N'New Mexico'),
	(N'Riverside',N'California'),
	(N'Riverton',N'Utah'),
	(N'Roanoke',N'Virginia'),
	(N'Rochester',N'Minnesota'),
	(N'Rochester',N'New York'),
	(N'Rochester Hills',N'Michigan'),
	(N'Rock Hill',N'South Carolina'),
	(N'Rock Island',N'Illinois'),
	(N'Rockford',N'Illinois'),
	(N'Rocklin',N'California'),
	(N'Rockville',N'Maryland'),
	(N'Rockwall',N'Texas'),
	(N'Rocky Mount',N'North Carolina'),
	(N'Rogers',N'Arkansas'),
	(N'Rohnert Park',N'California'),
	(N'Romeoville',N'Illinois'),
	(N'Rosemead',N'California'),
	(N'Roseville',N'California'),
	(N'Roseville',N'Michigan'),
	(N'Roswell',N'Georgia'),
	(N'Roswell',N'New Mexico'),
	(N'Round Rock',N'Texas'),
	(N'Rowlett',N'Texas'),
	(N'Roy',N'Utah'),
	(N'Royal Oak',N'Michigan'),
	(N'Sacramento',N'California'),
	(N'Saginaw',N'Michigan'),
	(N'Salem',N'Massachusetts'),
	(N'Salem',N'Oregon'),
	(N'Salina',N'Kansas'),
	(N'Salinas',N'California'),
	(N'Salt Lake City',N'Utah'),
	(N'Sammamish',N'Washington'),
	(N'San Angelo',N'Texas'),
	(N'San Antonio',N'Texas'),
	(N'San Bernardino',N'California'),
	(N'San Bruno',N'California'),
	(N'San Buenaventura (Ventura)',N'California'),
	(N'San Clemente',N'California'),
	(N'San Diego',N'California'),
	(N'San Francisco',N'California'),
	(N'San Gabriel',N'California'),
	(N'San Jacinto',N'California'),
	(N'San Jose',N'California'),
	(N'San Leandro',N'California'),
	(N'San Luis Obispo',N'California'),
	(N'San Marcos',N'California'),
	(N'San Marcos',N'Texas'),
	(N'San Mateo',N'California'),
	(N'San Rafael',N'California'),
	(N'San Ramon',N'California'),
	(N'Sandy',N'Utah'),
	(N'Sandy Springs',N'Georgia'),
	(N'Sanford',N'Florida'),
	(N'Santa Ana',N'California'),
	(N'Santa Barbara',N'California'),
	(N'Santa Clara',N'California'),
	(N'Santa Clarita',N'California'),
	(N'Santa Cruz',N'California'),
	(N'Santa Fe',N'New Mexico'),
	(N'Santa Maria',N'California'),
	(N'Santa Monica',N'California'),
	(N'Santa Rosa',N'California'),
	(N'Santee',N'California'),
	(N'Sarasota',N'Florida'),
	(N'Savannah',N'Georgia'),
	(N'Sayreville',N'New Jersey'),
	(N'Schaumburg',N'Illinois'),
	(N'Schenectady',N'New York'),
	(N'Scottsdale',N'Arizona'),
	(N'Scranton',N'Pennsylvania'),
	(N'Seattle',N'Washington'),
	(N'Shakopee',N'Minnesota'),
	(N'Shawnee',N'Kansas'),
	(N'Sheboygan',N'Wisconsin'),
	(N'Shelton',N'Connecticut'),
	(N'Sherman',N'Texas'),
	(N'Shoreline',N'Washington'),
	(N'Shreveport',N'Louisiana'),
	(N'Sierra Vista',N'Arizona'),
	(N'Simi Valley',N'California'),
	(N'Sioux City',N'Iowa'),
	(N'Sioux Falls',N'South Dakota'),
	(N'Skokie',N'Illinois'),
	(N'Smyrna',N'Georgia'),
	(N'Smyrna',N'Tennessee'),
	(N'Somerville',N'Massachusetts'),
	(N'South Bend',N'Indiana'),
	(N'South Gate',N'California'),
	(N'South Jordan',N'Utah'),
	(N'South San Francisco',N'California'),
	(N'Southaven',N'Mississippi'),
	(N'Southfield',N'Michigan'),
	(N'Spanish Fork',N'Utah'),
	(N'Sparks',N'Nevada'),
	(N'Spartanburg',N'South Carolina'),
	(N'Spokane',N'Washington'),
	(N'Spokane Valley',N'Washington'),
	(N'Springdale',N'Arkansas'),
	(N'Springfield',N'Illinois'),
	(N'Springfield',N'Massachusetts'),
	(N'Springfield',N'Missouri'),
	(N'Springfield',N'Ohio'),
	(N'Springfield',N'Oregon'),
	(N'St. Charles',N'Missouri'),
	(N'St. Clair Shores',N'Michigan'),
	(N'St. Cloud',N'Florida'),
	(N'St. Cloud',N'Minnesota'),
	(N'St. George',N'Utah'),
	(N'St. Joseph',N'Missouri'),
	(N'St. Louis',N'Missouri'),
	(N'St. Louis Park',N'Minnesota'),
	(N'St. Paul',N'Minnesota'),
	(N'St. Peters',N'Missouri'),
	(N'St. Petersburg',N'Florida'),
	(N'Stamford',N'Connecticut'),
	(N'Stanton',N'California'),
	(N'State College',N'Pennsylvania'),
	(N'Sterling Heights',N'Michigan'),
	(N'Stillwater',N'Oklahoma'),
	(N'Stockton',N'California'),
	(N'Streamwood',N'Illinois'),
	(N'Strongsville',N'Ohio'),
	(N'Suffolk',N'Virginia'),
	(N'Sugar Land',N'Texas'),
	(N'Summerville',N'South Carolina'),
	(N'Sumter',N'South Carolina'),
	(N'Sunnyvale',N'California'),
	(N'Sunrise',N'Florida'),
	(N'Surprise',N'Arizona'),
	(N'Syracuse',N'New York'),
	(N'Tacoma',N'Washington'),
	(N'Tallahassee',N'Florida'),
	(N'Tamarac',N'Florida'),
	(N'Tampa',N'Florida'),
	(N'Taunton',N'Massachusetts'),
	(N'Taylor',N'Michigan'),
	(N'Taylorsville',N'Utah'),
	(N'Temecula',N'California'),
	(N'Tempe',N'Arizona'),
	(N'Temple',N'Texas'),
	(N'Terre Haute',N'Indiana'),
	(N'Texarkana',N'Texas'),
	(N'Texas City',N'Texas'),
	(N'The Colony',N'Texas'),
	(N'Thornton',N'Colorado'),
	(N'Thousand Oaks',N'California'),
	(N'Tigard',N'Oregon'),
	(N'Tinley Park',N'Illinois'),
	(N'Titusville',N'Florida'),
	(N'Toledo',N'Ohio'),
	(N'Topeka',N'Kansas'),
	(N'Torrance',N'California'),
	(N'Tracy',N'California'),
	(N'Trenton',N'New Jersey'),
	(N'Troy',N'Michigan'),
	(N'Troy',N'New York'),
	(N'Tucson',N'Arizona'),
	(N'Tulare',N'California'),
	(N'Tulsa',N'Oklahoma'),
	(N'Turlock',N'California'),
	(N'Tuscaloosa',N'Alabama'),
	(N'Tustin',N'California'),
	(N'Twin Falls',N'Idaho'),
	(N'Tyler',N'Texas'),
	(N'Union City',N'California'),
	(N'Union City',N'New Jersey'),
	(N'Upland',N'California'),
	(N'Urbana',N'Illinois'),
	(N'Urbandale',N'Iowa'),
	(N'Utica',N'New York'),
	(N'Vacaville',N'California'),
	(N'Valdosta',N'Georgia'),
	(N'Vallejo',N'California'),
	(N'Valley Stream',N'New York'),
	(N'Vancouver',N'Washington'),
	(N'Victoria',N'Texas'),
	(N'Victorville',N'California'),
	(N'Vineland',N'New Jersey'),
	(N'Virginia Beach',N'Virginia'),
	(N'Visalia',N'California'),
	(N'Vista',N'California'),
	(N'Waco',N'Texas'),
	(N'Walnut Creek',N'California'),
	(N'Waltham',N'Massachusetts'),
	(N'Warner Robins',N'Georgia'),
	(N'Warren',N'Michigan'),
	(N'Warren',N'Ohio'),
	(N'Warwick',N'Rhode Island'),
	(N'Washington',N'District of Columbia'),
	(N'Waterbury',N'Connecticut'),
	(N'Waterloo',N'Iowa'),
	(N'Watsonville',N'California'),
	(N'Waukegan',N'Illinois'),
	(N'Waukesha',N'Wisconsin'),
	(N'Wausau',N'Wisconsin'),
	(N'Wauwatosa',N'Wisconsin'),
	(N'Wellington',N'Florida'),
	(N'Weslaco',N'Texas'),
	(N'West Allis',N'Wisconsin'),
	(N'West Covina',N'California'),
	(N'West Des Moines',N'Iowa'),
	(N'West Haven',N'Connecticut'),
	(N'West Jordan',N'Utah'),
	(N'West New York',N'New Jersey'),
	(N'West Palm Beach',N'Florida'),
	(N'West Sacramento',N'California'),
	(N'West Valley City',N'Utah'),
	(N'Westerville',N'Ohio'),
	(N'Westfield',N'Massachusetts'),
	(N'Westland',N'Michigan'),
	(N'Westminster',N'California'),
	(N'Westminster',N'Colorado'),
	(N'Weston',N'Florida'),
	(N'Weymouth Town',N'Massachusetts'),
	(N'Wheaton',N'Illinois'),
	(N'Wheeling',N'Illinois'),
	(N'White Plains',N'New York'),
	(N'Whittier',N'California'),
	(N'Wichita',N'Kansas'),
	(N'Wichita Falls',N'Texas'),
	(N'Wilkes-Barre',N'Pennsylvania'),
	(N'Wilmington',N'Delaware'),
	(N'Wilmington',N'North Carolina'),
	(N'Wilson',N'North Carolina'),
	(N'Winston-Salem',N'North Carolina'),
	(N'Winter Garden',N'Florida'),
	(N'Woburn',N'Massachusetts'),
	(N'Woodbury',N'Minnesota'),
	(N'Woodland',N'California'),
	(N'Woonsocket',N'Rhode Island'),
	(N'Worcester',N'Massachusetts'),
	(N'Wylie',N'Texas'),
	(N'Wyoming',N'Michigan'),
	(N'Yakima',N'Washington'),
	(N'Yonkers',N'New York'),
	(N'Yorba Linda',N'California'),
	(N'York',N'Pennsylvania'),
	(N'Youngstown',N'Ohio'),
	(N'Yuba City',N'California'),
	(N'Yucaipa',N'California'),
	(N'Yuma',N'Arizona')
) a (city, state);