
DROP TABLE IF EXISTS dbo.grocery_product;

CREATE TABLE dbo.grocery_product (
	product_name VARCHAR(50) NOT NULL
		CONSTRAINT uq_dbo_grocery_product UNIQUE (product_name),
	price MONEY NULL,
	category VARCHAR(50) NULL
		
);

INSERT INTO dbo.grocery_product(product_name,price,category)
SELECT 
	 a.product_name, a.price, a.category
FROM 
(
VALUES
	('Ground Beef (1 lb)','5.49','Meat & Seafood'),
	('Chicken Breast (1 lb)','4.29','Meat & Seafood'),
	('Pork Chops (1 lb)','4.19','Meat & Seafood'),
	('Bacon (16 oz)','6.49','Meat & Seafood'),
	('Whole Chicken (per lb)','2.19','Meat & Seafood'),
	('Salmon Fillet (1 lb)','9.99','Meat & Seafood'),
	('Shrimp - Frozen (1 lb)','8.99','Meat & Seafood'),
	('Turkey Breast (per lb)','4.99','Meat & Seafood'),
	('Deli Ham (per lb)','6.29','Meat & Seafood'),
	('Hot Dogs (10 ct)','3.49','Meat & Seafood'),
	('Whole Milk (1 gal)','3.89','Dairy & Eggs'),
	('Eggs (dozen)','2.99','Dairy & Eggs'),
	('Butter (1 lb)','4.79','Dairy & Eggs'),
	('Cheddar Cheese (8 oz)','3.99','Dairy & Eggs'),
	('Yogurt (single serve)','1.29','Dairy & Eggs'),
	('Sour Cream (16 oz)','2.29','Dairy & Eggs'),
	('Cream Cheese (8 oz)','2.49','Dairy & Eggs'),
	('Half & Half (1 pint)','2.39','Dairy & Eggs'),
	('Mozzarella (8 oz)','3.49','Dairy & Eggs'),
	('Cottage Cheese (16 oz)','2.89','Dairy & Eggs'),
	('White Bread (loaf)','2.79','Bakery & Grains'),
	('Whole Wheat Bread','3.29','Bakery & Grains'),
	('Hamburger Buns (8 ct)','2.49','Bakery & Grains'),
	('Bagels (6 ct)','3.99','Bakery & Grains'),
	('Flour (5 lb)','3.59','Bakery & Grains'),
	('Sugar (4 lb)','3.39','Bakery & Grains'),
	('Rice (2 lb)','2.49','Bakery & Grains'),
	('Spaghetti Pasta (1 lb)','1.49','Bakery & Grains'),
	('Cereal (box)','4.99','Bakery & Grains'),
	('Oats (18 oz)','3.29','Bakery & Grains'),
	('Olive Oil (16.9 oz)','7.49','Pantry Staples'),
	('Vegetable Oil (48 oz)','4.29','Pantry Staples'),
	('Salt (26 oz)','1.29','Pantry Staples'),
	('Black Pepper (3 oz)','3.49','Pantry Staples'),
	('Peanut Butter (16 oz)','2.99','Pantry Staples'),
	('Jelly (16 oz)','2.79','Pantry Staples'),
	('Honey (12 oz)','4.99','Pantry Staples'),
	('Soy Sauce (10 oz)','2.29','Pantry Staples'),
	('Ketchup (20 oz)','2.49','Pantry Staples'),
	('Mustard (14 oz)','1.89','Pantry Staples'),
	('Canned Tomatoes (14 oz)','1.49','Canned & Jarred Goods'),
	('Canned Corn','1.19','Canned & Jarred Goods'),
	('Canned Green Beans','1.19','Canned & Jarred Goods'),
	('Canned Tuna','1.39','Canned & Jarred Goods'),
	('Canned Chicken','2.79','Canned & Jarred Goods'),
	('Canned Soup (Campbell�s)','1.99','Canned & Jarred Goods'),
	('Pasta Sauce (24 oz)','2.79','Canned & Jarred Goods'),
	('Canned Beans (Black/Pinto)','1.29','Canned & Jarred Goods'),
	('Tomato Paste','0.89','Canned & Jarred Goods'),
	('Canned Chili','2.79','Canned & Jarred Goods'),
	('Bananas (per lb)','0.65','Fresh Produce'),
	('Apples (per lb)','1.89','Fresh Produce'),
	('Oranges (per lb)','1.49','Fresh Produce'),
	('Grapes (per lb)','2.79','Fresh Produce'),
	('Strawberries (1 lb)','3.49','Fresh Produce'),
	('Blueberries (6 oz)','3.79','Fresh Produce'),
	('Lemons (each)','0.79','Fresh Produce'),
	('Potatoes (5 lb bag)','3.29','Fresh Produce'),
	('Onions (3 lb bag)','2.99','Fresh Produce'),
	('Carrots (1 lb)','1.19','Fresh Produce'),
	('Lettuce (head)','1.79','Fresh Produce'),
	('Tomatoes (per lb)','2.49','Fresh Produce'),
	('Bell Peppers (each)','1.29','Fresh Produce'),
	('Cucumbers (each)','0.99','Fresh Produce'),
	('Avocados (each)','1.49','Fresh Produce'),
	('Garlic (bulb)','0.79','Fresh Produce'),
	('Spinach (bag)','3.29','Fresh Produce'),
	('Broccoli (bunch)','2.19','Fresh Produce'),
	('Celery (bunch)','1.99','Fresh Produce'),
	('Green Onions','0.89','Fresh Produce'),
	('Bottled Water (24 ct)','5.49','Beverages'),
	('Orange Juice (59 oz)','4.49','Beverages'),
	('Apple Juice (64 oz)','3.29','Beverages'),
	('Soda (2L)','1.99','Beverages'),
	('Coffee (ground - 12 oz)','6.99','Beverages'),
	('Tea Bags (100 ct)','4.29','Beverages'),
	('Energy Drinks (each)','2.79','Beverages'),
	('Sports Drink (32 oz)','1.69','Beverages'),
	('Almond Milk (half gal)','3.49','Beverages'),
	('Chocolate Milk (half gal)','2.99','Beverages'),
	('Frozen Pizza','5.99','Frozen Foods'),
	('Frozen Vegetables (16 oz)','1.79','Frozen Foods'),
	('Frozen Fruit (12 oz)','3.99','Frozen Foods'),
	('Ice Cream (1.5 qt)','5.49','Frozen Foods'),
	('Frozen Burritos','1.29','Frozen Foods'),
	('Frozen Chicken Nuggets','6.49','Frozen Foods'),
	('Frozen French Fries (2 lb)','3.49','Frozen Foods'),
	('Frozen Waffles','2.49','Frozen Foods'),
	('Frozen TV Dinner','3.99','Frozen Foods'),
	('Frozen Breakfast Sandwiches','4.99','Frozen Foods'),
	('Paper Towels (6 rolls)','8.49','Household & Cleaning'),
	('Toilet Paper (12 rolls)','9.99','Household & Cleaning'),
	('Dish Soap (16 oz)','2.59','Household & Cleaning'),
	('Laundry Detergent (100 oz)','12.99','Household & Cleaning'),
	('Bleach (1 gal)','3.49','Household & Cleaning'),
	('All-purpose Cleaner','3.29','Household & Cleaning'),
	('Trash Bags (30 ct)','6.99','Household & Cleaning'),
	('Sponges (pack of 4)','3.49','Household & Cleaning'),
	('Aluminum Foil (75 sq ft)','4.29','Household & Cleaning'),
	('Plastic Wrap (200 ft)','3.79','Household & Cleaning'),
	('Shampoo (12 oz)','4.49','Personal Care'),
	('Conditioner (12 oz)','4.49','Personal Care'),
	('Bar Soap (3 ct)','2.99','Personal Care'),
	('Body Wash (16 oz)','5.49','Personal Care'),
	('Toothpaste','3.99','Personal Care'),
	('Toothbrush','2.99','Personal Care'),
	('Deodorant','4.29','Personal Care'),
	('Razors (pack)','6.49','Personal Care'),
	('Lotion (12 oz)','5.29','Personal Care'),
	('Hand Sanitizer (8 oz)','2.99','Personal Care'),
	('Dry Dog Food (15 lb)','18.99','Pet Supplies'),
	('Wet Dog Food (can)','1.89','Pet Supplies'),
	('Dry Cat Food (7 lb)','13.99','Pet Supplies'),
	('Cat Litter (20 lb)','7.99','Pet Supplies'),
	('Dog Treats','4.49','Pet Supplies'),
	('Potato Chips (8 oz)','3.99','Snacks'),
	('Tortilla Chips','3.79','Snacks'),
	('Salsa (16 oz)','2.99','Snacks'),
	('Pretzels','2.99','Snacks'),
	('Crackers','3.49','Snacks'),
	('Granola Bars','3.99','Snacks'),
	('Popcorn (microwave - 6 ct)','3.49','Snacks'),
	('Trail Mix (10 oz)','4.79','Snacks'),
	('Cookies (packaged)','3.99','Snacks'),
	('Candy Bars','1.49','Snacks'),
	('Cake Mix','1.99','Desserts & Baking'),
	('Frosting','2.49','Desserts & Baking'),
	('Brownie Mix','1.99','Desserts & Baking'),
	('Chocolate Chips (12 oz)','2.99','Desserts & Baking'),
	('Pie Crust','2.99','Desserts & Baking'),
	('Pudding Mix','0.99','Desserts & Baking'),
	('Evaporated Milk','1.49','Desserts & Baking'),
	('Sweetened Condensed Milk','1.79','Desserts & Baking'),
	('Vanilla Extract (2 oz)','5.99','Desserts & Baking'),
	('Baking Powder','1.79','Desserts & Baking'),
	('Baby Formula (powder - 12 oz)','17.99','Baby & Kids'),
	('Baby Food (jar/pouch)','1.39','Baby & Kids'),
	('Diapers (pack of 30)','9.99','Baby & Kids'),
	('Baby Wipes (100 ct)','3.99','Baby & Kids'),
	('Kids Juice Boxes (10 ct)','3.99','Baby & Kids'),
	('Tortillas (10 ct)','2.49','International / Specialty'),
	('Ramen Noodles (6 pack)','2.49','International / Specialty'),
	('Coconut Milk (can)','2.29','International / Specialty'),
	('Curry Sauce','3.99','International / Specialty'),
	('Hummus (8 oz)','3.49','International / Specialty'),
	('Tofu (14 oz)','2.49','International / Specialty'),
	('Sriracha (17 oz)','4.49','International / Specialty'),
	('Naan Bread','3.29','International / Specialty'),
	('Miso Paste','4.99','International / Specialty'),
	('Kimchi (16 oz)','5.49','International / Specialty')
) a (product_name, price, category)