
DROP TABLE IF EXISTS dbo.product_convenience;

CREATE TABLE dbo.product_convenience (
	product_name VARCHAR(50) NOT NULL
		CONSTRAINT uq_dbo_product_convenience UNIQUE (product_name),
	price MONEY NULL,
	category VARCHAR(50) NULL
		
);

INSERT INTO dbo.product_convenience(product_name,price,category)
SELECT 
	 a.product_name, a.price, a.category
FROM 
(
VALUES
	('Bottled Water (16.9 oz)','1.29','Beverages'),
	('Soda (20 oz)','1.99','Beverages'),
	('Energy Drink (16 oz)','2.79','Beverages'),
	('Iced Tea (16 oz)','1.89','Beverages'),
	('Sports Drink (20 oz)','1.69','Beverages'),
	('Coffee (medium)','1.99','Beverages'),
	('Slushie (medium)','2.49','Beverages'),
	('Milk (pint)','1.49','Beverages'),
	('Juice Box','0.99','Beverages'),
	('Cold Brew Coffee','3.49','Beverages'),
	('Chocolate Milk (pint)','1.69','Beverages'),
	('Sparkling Water (can)','1.49','Beverages'),
	('Protein Shake (bottle)','3.99','Beverages'),
	('Vitamin Water','2.19','Beverages'),
	('Coconut Water','2.79','Beverages'),
	('Potato Chips (2 oz)','1.49','Snacks'),
	('Tortilla Chips (2 oz)','1.49','Snacks'),
	('Beef Jerky (2 oz)','4.99','Snacks'),
	('Trail Mix (2 oz)','1.99','Snacks'),
	('Granola Bar','1.29','Snacks'),
	('Crackers (single serve)','1.49','Snacks'),
	('Snack Mix','1.89','Snacks'),
	('Nuts (1 oz)','1.79','Snacks'),
	('Cheese Crackers','1.49','Snacks'),
	('Rice Cakes','1.29','Snacks'),
	('Popcorn (bag)','1.59','Snacks'),
	('Pretzels (2 oz)','1.49','Snacks'),
	('Fruit Snacks','0.99','Snacks'),
	('Dried Fruit (bag)','2.99','Snacks'),
	('Peanut Butter Crackers','1.49','Snacks'),
	('Chocolate Bar','1.49','Candy'),
	('Gummy Bears','1.29','Candy'),
	('Hard Candy','0.99','Candy'),
	('Licorice','1.49','Candy'),
	('Mints','1.29','Candy'),
	('Candy Bar (King Size)','2.19','Candy'),
	('Lollipops','0.5','Candy'),
	('Sour Candy','1.39','Candy'),
	('Caramel Candy','1.19','Candy'),
	('Cotton Candy','1.99','Candy'),
	('Chocolate Covered Nuts','2.29','Candy'),
	('Jelly Beans','1.49','Candy'),
	('Taffy','1.29','Candy'),
	('Candy-Coated Chocolates','1.59','Candy'),
	('Chewing Gum','1.09','Candy'),
	('Cigarettes (pack)','9.99','Tobacco'),
	('Cigars','2.49','Tobacco'),
	('Lighter','1.29','Tobacco'),
	('Rolling Papers','1.19','Tobacco'),
	('Vape Pen','14.99','Tobacco'),
	('Nicotine Gum','5.99','Tobacco'),
	('Tobacco Pipe','6.99','Tobacco'),
	('Ashtray','3.99','Tobacco'),
	('Butane Canister','4.49','Tobacco'),
	('E-liquid Bottle','9.99','Tobacco'),
	('Beer (can)','2.49','Alcohol'),
	('Wine (mini bottle)','3.99','Alcohol'),
	('Malt Beverage','2.79','Alcohol'),
	('Hard Seltzer (can)','2.99','Alcohol'),
	('Vodka Mini Bottle','1.99','Alcohol'),
	('Whiskey Mini Bottle','2.29','Alcohol'),
	('Rum Mini Bottle','2.29','Alcohol'),
	('Pre-Mixed Cocktail (can)','3.49','Alcohol'),
	('Hard Cider','2.49','Alcohol'),
	('Gin Mini Bottle','2.49','Alcohol'),
	('Microwave Burrito','2.49','Packaged Foods'),
	('Cup Noodles','1.29','Packaged Foods'),
	('Instant Soup','1.69','Packaged Foods'),
	('Frozen Pizza Slice','2.99','Packaged Foods'),
	('Canned Chili','2.49','Packaged Foods'),
	('Mac and Cheese Cup','1.89','Packaged Foods'),
	('Toaster Pastry','1.79','Packaged Foods'),
	('Frozen Breakfast Sandwich','2.99','Packaged Foods'),
	('Peanut Butter Jar','3.49','Packaged Foods'),
	('Jelly Jar','2.99','Packaged Foods'),
	('Canned Tuna','1.59','Packaged Foods'),
	('Cereal Box (small)','2.99','Packaged Foods'),
	('Oatmeal Pack','0.99','Packaged Foods'),
	('Crackers Box','2.49','Packaged Foods'),
	('Rice (1 lb bag)','1.99','Packaged Foods'),
	('Toothpaste','1.99','Personal Care'),
	('Toothbrush','1.49','Personal Care'),
	('Deodorant','3.29','Personal Care'),
	('Shampoo (travel size)','1.49','Personal Care'),
	('Conditioner (travel size)','1.49','Personal Care'),
	('Comb','0.99','Personal Care'),
	('Razor','2.29','Personal Care'),
	('Shaving Cream','1.99','Personal Care'),
	('Lip Balm','1.29','Personal Care'),
	('Feminine Pads (pack)','2.99','Personal Care'),
	('Tampons (pack)','3.49','Personal Care'),
	('Hand Sanitizer','1.49','Personal Care'),
	('Face Wipes','1.99','Personal Care'),
	('Nail Clippers','1.49','Personal Care'),
	('Cotton Swabs','1.29','Personal Care'),
	('Pain Reliever (small)','2.49','Health'),
	('Cough Drops','1.29','Health'),
	('Allergy Relief','3.49','Health'),
	('Antacid Tablets','2.29','Health'),
	('Bandages (pack)','1.99','Health'),
	('First Aid Kit','6.99','Health'),
	('Thermometer','5.99','Health'),
	('Cold Medicine (small)','4.49','Health'),
	('Vitamins (travel pack)','2.99','Health'),
	('Hand Warmers','1.99','Health'),
	('Trash Bags (small pack)','2.99','Household'),
	('Paper Towels (roll)','1.49','Household'),
	('Toilet Paper (roll)','1.29','Household'),
	('Cleaning Wipes','2.99','Household'),
	('Dish Soap (small)','1.49','Household'),
	('Light Bulb','1.99','Household'),
	('Laundry Detergent (small)','2.99','Household'),
	('Air Freshener (house)','1.49','Household'),
	('Batteries (2 pack)','3.49','Household'),
	('Plastic Utensils','1.29','Household'),
	('Motor Oil (quart)','5.99','Automotive'),
	('Windshield Washer Fluid','3.49','Automotive'),
	('Air Freshener (auto)','2.49','Automotive'),
	('Jumper Cables','14.99','Automotive'),
	('Fuses','1.49','Automotive'),
	('Tire Gauge','2.99','Automotive'),
	('Ice Scraper','3.49','Automotive'),
	('Car Wipes','2.99','Automotive'),
	('Phone Charger','9.99','Automotive'),
	('USB Cable','5.99','Automotive'),
	('Umbrella','7.99','Miscellaneous'),
	('Keychain','2.99','Miscellaneous'),
	('Gift Card','25.0','Miscellaneous'),
	('Phone Card','10.0','Miscellaneous'),
	('Pen','0.99','Miscellaneous'),
	('Notebook','1.99','Miscellaneous'),
	('Flashlight','4.99','Miscellaneous'),
	('Scissors','2.49','Miscellaneous'),
	('Earbuds','9.99','Miscellaneous'),
	('Balloons (pack)','1.49','Miscellaneous')
) a (product_name, price, category)